# Generated by Django 5.0.6 on 2024-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
